### ISSUE TITLE
雷电9崩溃

### ISSUE THREAD

**Issue by hang0526** [LLeavesG/Frida-Sigaction-Seccomp#1]
C:\Users\hang\Downloads>frida -U -f com.fenfei.syscalldemo -l sigaction.js
     ____
    / _  |   Frida 16.5.7 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to Android Emulator 5554 (id=emulator-5554)
Spawned `com.fenfei.syscalldemo`. Resuming main thread!
[Android Emulator 5554::com.fenfei.syscalldemo ]-> Process crashed: Trace/BPT trap

***
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/star2qltezh/star2qltechn:9/PQ3B.190801.10101846/G9650ZHU2ARC6:user/release-keys'
Revision: '0'
ABI: 'x86'
pid: 3963, tid: 3963, name: fei.syscalldemo  >>> com.fenfei.syscalldemo <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
    eax 00000000  ebx 00000f7b  ecx 00000f7b  edx 00000006
    edi 00000002  esi fffffffb
    ebp f76c3734  esp f7e98a18  eip f7ea1cd9

backtrace:
    #00 pc 00000cd9  [vdso:f7ea1000] (__kernel_vsyscall+9)
    #01 pc 0001fae8  /system/lib/libc.so (offset 0x1f000) (syscall+40)
    #02 pc 00032f73  /system/lib/libc.so (offset 0x32000) (abort+115)
    #03 pc 0000040e  <anonymous:f3beb000>
***
[Android Emulator 5554::com.fenfei.syscalldemo ]->

Thank you for using Frida!
雷电9模拟器 应用是32位的 我试了几个应用都是一样的报错原因

**Comment by LLeavesG** [comment]
应用32位需要修改js里面c实现那块的代码，32位和64位在进行系统调用的时候有不一样的地方

**Comment by LLeavesG** [comment]
也也可能是别的原因，先试试64位app，如果还是不行就手动排查吧

**Comment by hang0526** [comment]
我尝试了几个64位一样的报错 都是报signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
